---
- name: Ensure web root exists (Debian/Ubuntu)
  ansible.builtin.file:
    path: "{{ nginx_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  when: ansible_facts['os_family'] == 'Debian'

- name: Upload website tarball
  ansible.builtin.copy:
    src: website.tar.gz
    dest: /tmp/website.tar.gz
    mode: '0644'

- name: Unpack website into web root (strip top-level dir)
  ansible.builtin.unarchive:
    src: /tmp/website.tar.gz
    dest: "{{ nginx_root }}"
    remote_src: true
    extra_opts: ['--strip-components=1']
  notify: restart nginx

- name: Ensure web root ownership (recursive)
  ansible.builtin.file:
    path: "{{ nginx_root }}"
    owner: www-data
    group: www-data
    recurse: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Remove default Debian index page
  ansible.builtin.file:
    path: "{{ nginx_root }}/index.nginx-debian.html"
    state: absent
  when: ansible_facts['os_family'] == 'Debian'
