# roles/nodejs/tasks/main.yml
- name: Install Node.js repository
  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  
- name: Install Node.js and npm
  ansible.builtin.apt:
    name: nodejs
    state: present
    
- name: Install PM2 globally
  community.general.npm:
    name: pm2
    global: yes